Repository SM-Blow/blow-server, pull requests merged in 2023-09, with the labels that each got.

#34 [FEAT🛠️] 푸시알림 구현
  .gitignore
  build.gradle
  src/main/java/com/blow/server/api/common/ErrorHandler.java
  src/main/java/com/blow/server/api/common/exception/FcmException.java
  src/main/java/com/blow/server/api/common/message/ExceptionMessage.java
  src/main/java/com/blow/server/api/common/message/ResponseMessage.java
  src/main/java/com/blow/server/api/config/FCMConfig.java
  src/main/java/com/blow/server/api/controller/AuthController.java
  src/main/java/com/blow/server/api/controller/FCMController.java
  src/main/java/com/blow/server/api/dto/auth/request/LoginRequestDTO.java
  src/main/java/com/blow/server/api/dto/auth/request/SignInRequestDTO.java
  src/main/java/com/blow/server/api/dto/notification/request/FCMRequestDTO.java
  src/main/java/com/blow/server/api/entity/User.java
  src/main/java/com/blow/server/api/service/auth/AuthServiceImpl.java
  src/main/java/com/blow/server/api/service/notification/FCMService.java
  src/main/java/com/blow/server/api/service/notification/FCMServiceImpl.java
Labels: feat, size/L, gahee

#35 feat:scrap-post 기능 개발
  src/main/java/com/blow/server/api/common/message/ExceptionMessage.java
  src/main/java/com/blow/server/api/common/message/ResponseMessage.java
  src/main/java/com/blow/server/api/controller/PostController.java
  src/main/java/com/blow/server/api/dto/Post/request/PostScrapRequestDTO.java
  src/main/java/com/blow/server/api/dto/Post/response/PostScrapResponseDTO.java
  src/main/java/com/blow/server/api/dto/Post/response/PostScrapsResponseDTO.java
  src/main/java/com/blow/server/api/entity/Post.java
  src/main/java/com/blow/server/api/entity/PostScrap.java
  src/main/java/com/blow/server/api/entity/User.java
  src/main/java/com/blow/server/api/repository/PostScrapRepository.java
  src/main/java/com/blow/server/api/service/Post/PostService.java
  src/main/java/com/blow/server/api/service/Post/PostServiceImpl.java
Labels: feat, size/M, juyoung

#37 [FEAT🛠️] 기능 확장에 따른 엔티티 추가
  src/main/java/com/blow/server/api/entity/Coupon.java
  src/main/java/com/blow/server/api/entity/Event.java
  src/main/java/com/blow/server/api/entity/EventApply.java
  src/main/java/com/blow/server/api/entity/Report.java
  src/main/java/com/blow/server/api/entity/User.java
Labels: feat, size/M, gahee

#40 Feat/#21 mypage
  src/main/java/com/blow/server/api/common/message/ResponseMessage.java
  src/main/java/com/blow/server/api/controller/PostController.java
  src/main/java/com/blow/server/api/controller/UserController.java
  src/main/java/com/blow/server/api/dto/post/request/PostCreateRequestDTO.java
  src/main/java/com/blow/server/api/dto/post/request/PostDeleteRequestDTO.java
  src/main/java/com/blow/server/api/dto/post/request/PostEditRequestDTO.java
  src/main/java/com/blow/server/api/dto/post/request/PostEditStatusRequestDTO.java
  src/main/java/com/blow/server/api/dto/post/request/PostScrapRequestDTO.java
  src/main/java/com/blow/server/api/dto/post/response/PostDetailResponseDTO.java
  src/main/java/com/blow/server/api/dto/post/response/PostResponseDTO.java
  src/main/java/com/blow/server/api/dto/post/response/PostScrapResponseDTO.java
  src/main/java/com/blow/server/api/dto/post/response/PostScrapsResponseDTO.java
  src/main/java/com/blow/server/api/dto/post/response/PostSearchResponseDTO.java
  src/main/java/com/blow/server/api/dto/user/UserMyPageResponseDTO.java
  src/main/java/com/blow/server/api/entity/Report.java
  src/main/java/com/blow/server/api/repository/PostRepository.java
  src/main/java/com/blow/server/api/service/Post/PostService.java
  src/main/java/com/blow/server/api/service/Post/PostServiceImpl.java
  src/main/java/com/blow/server/api/service/user/UserService.java
  src/main/java/com/blow/server/api/service/user/UserServiceImpl.java
Labels: feat, size/M, juyoung

#41 fix : postList JPA method로 정렬함
  src/main/java/com/blow/server/api/repository/PostRepository.java
  src/main/java/com/blow/server/api/service/user/UserServiceImpl.java
Labels: feat, size/S, juyoung

#42 Feat/#39 event api
  src/main/java/com/blow/server/api/common/ErrorHandler.java
  src/main/java/com/blow/server/api/common/exception/EventException.java
  src/main/java/com/blow/server/api/common/exception/RentalException.java
  src/main/java/com/blow/server/api/common/message/ExceptionMessage.java
  src/main/java/com/blow/server/api/common/message/ResponseMessage.java
  src/main/java/com/blow/server/api/controller/EventController.java
  src/main/java/com/blow/server/api/dto/event/request/CreateEventRequestDTO.java
  src/main/java/com/blow/server/api/dto/event/response/EventDetailResponseDTO.java
  src/main/java/com/blow/server/api/dto/event/response/EventListResponseDTO.java
  src/main/java/com/blow/server/api/dto/event/response/EventMyApplyResponseDTO.java
  src/main/java/com/blow/server/api/entity/Event.java
  src/main/java/com/blow/server/api/entity/EventApply.java
  src/main/java/com/blow/server/api/repository/EventApplyRepository.java
  src/main/java/com/blow/server/api/repository/EventRepository.java
  src/main/java/com/blow/server/api/repository/UserRepository.java
  src/main/java/com/blow/server/api/service/event/EventService.java
  src/main/java/com/blow/server/api/service/event/EventServiceImpl.java
  src/main/java/com/blow/server/api/service/user/UserDetailsServiceImpl.java
Labels: feat, size/L, gahee

#46 feat:홈 화면 api 개발
  src/main/java/com/blow/server/api/common/message/ResponseMessage.java
  src/main/java/com/blow/server/api/controller/HomeController.java
  src/main/java/com/blow/server/api/dto/home/response/HomeResponseDTO.java
  src/main/java/com/blow/server/api/service/home/HomeService.java
  src/main/java/com/blow/server/api/service/home/HomeServiceImpl.java
Labels: feat, size/S, juyoung

#47 Feat/#43 coupon api
  src/main/java/com/blow/server/api/common/message/ExceptionMessage.java
  src/main/java/com/blow/server/api/common/message/ResponseMessage.java
  src/main/java/com/blow/server/api/controller/CouponController.java
  src/main/java/com/blow/server/api/dto/coupon/request/CouponRegistRequestDTO.java
  src/main/java/com/blow/server/api/dto/coupon/request/CouponUseRequestDTO.java
  src/main/java/com/blow/server/api/dto/coupon/response/CouponResponseDTO.java
  src/main/java/com/blow/server/api/entity/Coupon.java
  src/main/java/com/blow/server/api/entity/Report.java
  src/main/java/com/blow/server/api/entity/User.java
  src/main/java/com/blow/server/api/repository/CouponRepository.java
  src/main/java/com/blow/server/api/service/Post/PostServiceImpl.java
  src/main/java/com/blow/server/api/service/coupon/CouponService.java
  src/main/java/com/blow/server/api/service/coupon/CouponServiceImpl.java
Labels: feat, size/L, juyoung

#50 feat: swagger 적용
  build.gradle
  src/main/java/com/blow/server/api/config/SwaggerConfig.java
Labels: feat, size/S, juyoung

#54 feat : swagger config update
  src/main/java/com/blow/server/api/config/SwaggerConfig.java
Labels: feat, size/S, juyoung

#55 feat:씨앗 로직 추가
  src/main/java/com/blow/server/api/common/message/ResponseMessage.java
  src/main/java/com/blow/server/api/config/SwaggerConfig.java
  src/main/java/com/blow/server/api/dto/home/response/HomeResponseDTO.java
  src/main/java/com/blow/server/api/dto/post/request/PostEditStatusRequestDTO.java
  src/main/java/com/blow/server/api/dto/user/UserMyPageResponseDTO.java
  src/main/java/com/blow/server/api/entity/User.java
  src/main/java/com/blow/server/api/service/Post/PostServiceImpl.java
  src/main/java/com/blow/server/api/service/auth/AuthServiceImpl.java
Labels: feat, size/S, juyoung
